### ISSUE TITLE
Error when parent is null

### ISSUE THREAD

**Issue by EpicKnarvik97** [fdett/jellyfin-ignore#2]
This plugin produces an error for my files with extras, and some other items, when scanning my library. I reported it to Jellyfin first [here](https://github.com/jellyfin/jellyfin/issues/10408), but was told it was a problem with this plugin specifically. According to the response I got, the cause of the error lies at [this location](https://github.com/fdett/jellyfin-ignore/blob/master/Jellyfin.Plugin.Ignore/IgnoreRule.cs#L61) and is caused by the parent element being null, which isn't accounted for.

```
[2024-03-20 20:21:18.605 +01:00] [ERR] Error refreshing owned items for "/movies/Folder (Year) [imdbid-tt0000000]/Movie (Year) [imdbid-tt0000000].mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.Ignore.IgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
   at Emby.Server.Implementations.Library.LibraryManager.<FindExtras>g__GetExtra|168_0(FileSystemMetadata file, ExtraType extraType, <>c__DisplayClass168_0& )
   at Emby.Server.Implementations.Library.LibraryManager.FindExtras(BaseItem owner, IReadOnlyList`1 fileSystemChildren, IDirectoryService directoryService)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshExtras(BaseItem item, MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshedOwnedItems(MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Video.RefreshedOwnedItems(MetadataRefreshOptions options, IReadOnlyList`1 fileSystemChildren, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
```

**Comment by fdett** [comment]
Hi @EpicKnarvik97, if you're on Jellyfin 10.9+, the latest release (v0.5) should fix this.
